### ISSUE TITLE
Document that this is a browser-based library; point to Node utilities

### ISSUE THREAD

**Issue by willemneal** [solid/solid-auth-client#66]
Is there an example of how to login in using node?

**Comment by pavittarx** [comment]
This should be the part of docs, it took me around two days to reach here, I was about to open an issue, before I stumbled upon this. 

Thanks. 

Also why are login() and other methods not usable from within NodeJS? It throws an `window` is not defined error.

**Comment by pavittarx** [comment]
> Feel free to add a suggestions as a PR.

Thank you, I'll add my suggestion soon. 

Also this part in docs, gives an impression that `solid-auth-client` can be used with NodeJs, what is this for? It is present in the `readme` of this repo.
> In Node.js, run npm install solid-auth-client and then do:
```
const auth = require('solid-auth-client')

auth.trackSession(session => {
  if (!session)
    console.log('The user is not logged in')
  else
    console.log(`The user is ${session.webId}`)
})
```

> Don't hesitate do reach out on our Gitter channels i

It is just because, there are no links or information about support channels, I didn't have clue about it. I recently joined https://gitter.im/solid/chat Please let me know, if there are any others.

Thank you.

**Comment by RubenVerborgh** [comment]
Some inspiration in #72.

**Comment by megoth** [comment]
> It is just because, there are no links or information about support channels, I didn't have clue about it. I recently joined https://gitter.im/solid/chat Please let me know, if there are any others.

I guess you've seen this in Gitter, but just in case; We've opened a forum now ^_^ https://forum.solidproject.org/
